// Given a string, we have to find out all its subsequences of it.
// A String is a subsequence of a given String,
// that is generated by deleting some character of a given string without changing its order.

/**
 * Adopt the pick & leave mechanism.
 *  str: abc
 *  we start with inputStr = abc & outputStr = ""
 * generate(inputStr.sub(1), `${outStr}inputSub[0]`) // include [1]
 * generate(inputStr.sub(1), outStr) // exclude [0]
 *
 * base condition : inpStr.length === 0, outStr is valid output
 */
const printAllSubSequence = (str: string): string[] => {
    const res: string[] = [];
    const generate = (inp: string, opt: string) => {
        if (inp.length === 0) {
            res.push(opt);
            return;
        }

        generate(inp.substring(1), `${opt}${inp[0]}`);
        generate(inp.substring(1), opt);
    };

    generate(str, '');
    return res;
};

console.log('All subsequences of', 'abc', printAllSubSequence('abc'));
console.log('All subsequences of', 'geeks', printAllSubSequence('geeks'));
