/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */

function findTheDifference(s: string, t: string): string {
    const map: { [k in string]: number } = {};
    for (let i = 0; i < s.length; i++) {
        map[s[i]] = map[s[i]] || 0;
        map[s[i]]++;
    }

    for (let i = 0; i < t.length; i++) {
        if (!map[t[i]]) return t[i];
        else map[t[i]]--;
    }

    return '';
}

console.log(findTheDifference('abcd', 'abcde'));
console.log(findTheDifference('', 'y'));
console.log(findTheDifference('y', 'ay'));
