/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 */

function findTheDifference(s: string, t: string): string {
    const map: { [k in string]: number } = {};
    for (const c of s) {
        map[c] = map[c] || 0;
        map[c]++;
    }

    for (const c of t) {
        if (!map[c]) return c;
        map[c]--;
    }
    return '';
}

console.log(findTheDifference('abcd', 'abcde'));
console.log(findTheDifference('yab', 'yabc'));
